### ISSUE TITLE
Just wanted to know what is the use of asyncHandler

### ISSUE THREAD

**Issue by bozzmob** [manikandanraji/youtubeclone-backend#1]
Hi @manikandanraji ,

Just wanted to know what is the use of asyncHandler wrapper function.
```
const asyncHandler = (fn) => (req, res, next) =>
  Promise.resolve(fn(req, res, next)).catch(next);

module.exports = asyncHandler;
```

**Comment by manikandanraji** [comment]
In our handlers, we typically catch errors like this:

```javascript
app.get('/someendpoint', async (req, res) => {
	try {
	  const data = await operationThatMayThrowError();
           // perform actions here...
	} catch(err) {
	  // send back appropriated err response
	}
})
```
But instead of doing this for every single one of our handlers, we can write a higher order function which will take our function and try to execute it, if there is any error, the error will be passed to the errorHandler middleware 

So our handlers code looks clean and tidy and the errorHandler middleware will handle the errors. If you are still confused take a look at this blog post: https://www.acuriousanimal.com/blog/2018/03/15/express-async-middleware

**Comment by bozzmob** [comment]
Impressive! Great job. That's a very nice blog post.

**Comment by bozzmob** [comment]
Hi, this is not related to the above question, but, how would you handle 404's? Does the 500 in error handler also handle 404?

**Comment by manikandanraji** [comment]
If any error occurs in our handler, the middleware 'errorHandler' will be called. We pass an object to the 'errorHandler' middleware, the 'errorHandler' then send back approriate error response and statusCode to the client or the whom requested it.

The middleware chain looks like this:

request coming in --> our endpoints handler(if any error occurs, call errroHandler) --> errorHandler

The error object that we pass to looks like this for 404 error:

```javascript
{
	statusCode: 404,
	message: 'The requested videoId is not found'
}
```

For protected routes (routes that only registered users can access), the authorized looks like this:

```javascript
{
	statusCode: 401,
	message: 'You need to loggedin to visit this route'
}
```

If we don't pass any object the errorHandler middleware (as we cannot determine how certain errors beforehand), the default result will be:

```javascript
{
	statusCode: 500,
	message: 'Internal Server Error'
}
```

You can see the errorHandler in details here: https://github.com/manikandanraji/youtubeclone-backend/blob/master/src/middlewares/errorHandler.js
